### ISSUE TITLE
Ahoy regelt zu weit runter, unter 2%-Regel!

### ISSUE THREAD

**Issue by DanielR92** [DanielR92/ahoy#3]
Es wird zu weit runter geregelt, so das der Inverter sich schlafen legt, oder sogar ganz aus geht. Wir sollten das Minimum von 2% beachten !

**Comment by knickohr** [comment]
Das Minimum ist aber auf einkanalige Inverter bezogen. Bei zweikanaligen kann es höher sein weil beide Kanäle simultan geregelt werden. Auch kann es sein das es bei Invertern mit mehr Leistung kleiner ist. Vielleicht muß man das nicht relativ sondern absolut machen ?

**Comment by knickohr** [comment]
Könnte tatsächlich passen. Würde dann auch bei den „mehrhändigen“ passen

**Comment by DanielR92** [comment]
Ich close das schonmal... kommt im neuen commit.
