### ISSUE TITLE
Feature Request :  keine alten Power Limits senden

### ISSUE THREAD

**Issue by knickohr** [DanielR92/ahoy#9]
Wie schon in Issue #8 erwähnt ist es dem Inverter unangenehm, wenn man vor dem Ack ein neues Limir sendet. Weiterhin scheint ihm nicht zu schmecken wenn ein alter Limit-Wert wiederholt wird. Im schlimmsten Fall kann das soweit gehen das er sich schlafen legt und erst nach ca. 15min wieder zur Kooperation bereit ist. Im besten Fall quittiert er das neu gesetzte Limit mit gleichen Wert nur ohne ein darauffolgendes Ack, läßt dieses also einfach aus.

Lösung :  nur veränderte Power-Limit Werte senden

**Comment by DanielR92** [comment]
Was heißt alter Limit-Wert wiederholt wird? 
Meinst du das "Paket" neu gesendet wird, oder alleine der Power-Wert?

Denn jedes Paket wird mittels Timestamp neu geschickt.

**Comment by knickohr** [comment]
Nein, wen. Du z.B. vorher 40 gesendet hast, dann darf nicht nochmal 40 gesendet werde. Außer der Wert ändert sich.

**Comment by DanielR92** [comment]
Ist nun mit intigriert. Danke fürs Feedback! :)
https://github.com/DanielR92/ahoy/commit/2e50250dcd252d94ecccecf94a555083c5a91628
